# Rigged walk test v1: one skinned v6 guest body per sex with a humanoid armature and "walk" + "idle" animations.
#   blender -b --python build_rigged.py -- <female|male> <out_dir>
# The body is generated by the designer's attendee-v6-draft/build_attendee.py (relaxed pose), so it matches the shipped
# v6 bodies: same parts, palette material and slot contract. The baked hair is left out (hair is a sibling piece now);
# attach hair, hats and glasses to the Head bone. Bone names follow Godot's SkeletonProfileHumanoid.
# Blender +Y = front (Godot -Z after export), origin at foot ground centre, real metres.
import bpy, bmesh, math, sys, os, json, hashlib
from mathutils import Vector as V, Matrix, Quaternion

argv = sys.argv[sys.argv.index("--") + 1:]
SEX, OUT = argv[0], argv[1]; os.makedirs(OUT, exist_ok=True)
ROOT = "C:/Projects/festival-tycoon/assets/source/characters/"
GEN = ROOT + "attendee-v6-draft/build_attendee.py"
NAME = f"lwf_attendee_{SEX}_rigged_test_v1"
FPS, WALK_N, IDLE_N = 24, 28, 49            # walk: 27 intervals = 1.125 s per two steps; idle: 2.0 s

# ---------------------------------------------------------------- generate the relaxed v6 body
g = dict(__name__="__gen__")
sys.argv = [sys.argv[0], "--", SEX, os.path.join(OUT, "_scratch.blend"), ROOT + f"attendee-v6-draft/{SEX}-attendee-v6.blend", "relaxed"]
exec(compile(open(GEN).read(), GEN, "exec"), g)
body, K, S, relaxed_joints = g["body"], g["K"], g["S"], g["relaxed_joints"]
F = SEX == "female"
for f in ("_scratch.blend", "_scratch.glb", "_scratch.json"):
    p = os.path.join(OUT, f)
    if os.path.exists(p): os.remove(p)
for o in [o for o in bpy.data.objects if o is not body]: bpy.data.objects.remove(o)

# part of every vertex (generator vertex groups), then drop the hair
me = body.data
gname = {vg.index: vg.name for vg in body.vertex_groups}
vpart = [gname[v.groups[0].group] for v in me.vertices]
bm = bmesh.new(); bm.from_mesh(me)
dl = bm.verts.layers.deform.active
bmesh.ops.delete(bm, geom=[v for v in bm.verts if gname[next(iter(v[dl].keys()))] == "Hair"], context='VERTS')
bm.to_mesh(me); bm.free()
vpart = [gname[v.groups[0].group] for v in me.vertices]
body.name = "LWF_Attendee_Body"; me.name = "LWF_Attendee_Body"

# torso tee island = the largest Tee island (compared by face-index sets); other Tee islands are sleeves
bm = bmesh.new(); bm.from_mesh(me); bm.faces.ensure_lookup_table()
def islands(faces):
    faces = set(faces); seen = set(); out = []
    for f in faces:
        if f in seen: continue
        st, comp = [f], []
        while st:
            x = st.pop()
            if x in seen: continue
            seen.add(x); comp.append(x)
            for e in x.edges: st += [h for h in e.link_faces if h in faces and h not in seen]
        out.append(comp)
    return out
tee_islands = islands([f for f in bm.faces if vpart[f.verts[0].index] == "Tee"])
torso_verts = {v.index for v in {v for f in max(tee_islands, key=len) for v in f.verts}}
bm.free()

# ---------------------------------------------------------------- joints (final metres)
sh = {sx: relaxed_joints(sx)[0] * K for sx in (-1, 1)}
el = {sx: relaxed_joints(sx)[1] * K for sx in (-1, 1)}
wr = {sx: relaxed_joints(sx)[2] * K for sx in (-1, 1)}
hand_end = {sx: wr[sx] + V((sx * 0.004, 0.006, -1)).normalized() * 0.095 for sx in (-1, 1)}
hipz = 0.86 * S * K
hip = {sx: V((sx * 0.080, 0.0, 0.84 * S)) * K for sx in (-1, 1)}
knee = {sx: V((sx * 0.080 * 1.05, 0.010, 0.47 * S)) * K for sx in (-1, 1)}
ankle = {sx: V((sx * 0.080 * 1.09, 0.0, 0.10)) * K for sx in (-1, 1)}
toe = {sx: V((sx * 0.088 * K, 0.17, 0.035)) for sx in (-1, 1)}
heads = [V(me.vertices[i].co) for i in range(len(me.vertices)) if vpart[i] == "Head"]
head_top = max(v.z for v in heads)
neck_vs = [v for v in heads if abs(v.x) < 0.06 and v.y < 0.03]
chin = g["cz"] * K          # chin height in build units scaled (head_tf keeps the chin level for d.z >= 0)
neck_base = 1.36 * S * K
BONES = {  # name: (head, tail, parent)
    "Hips": (V((0, 0, hipz)), V((0, 0, hipz + 0.10)), None),
    "Spine": (V((0, 0, hipz + 0.10)), V((0, 0, 1.12 * S * K)), "Hips"),
    "Chest": (V((0, 0, 1.12 * S * K)), V((0, -0.01, neck_base)), "Spine"),
    "Neck": (V((0, -0.01, neck_base)), V((0, 0.0, chin)), "Chest"),
    "Head": (V((0, 0.0, chin)), V((0, 0.0, head_top)), "Neck"),
}
for sx, side in ((-1, "Left"), (1, "Right")):
    BONES[f"{side}UpperArm"] = (sh[sx], el[sx], "Chest")
    BONES[f"{side}LowerArm"] = (el[sx], wr[sx], f"{side}UpperArm")
    BONES[f"{side}Hand"] = (wr[sx], hand_end[sx], f"{side}LowerArm")
    BONES[f"{side}UpperLeg"] = (hip[sx], knee[sx], "Hips")
    BONES[f"{side}LowerLeg"] = (knee[sx], ankle[sx], f"{side}UpperLeg")
    BONES[f"{side}Foot"] = (ankle[sx], toe[sx], f"{side}LowerLeg")

arm_data = bpy.data.armatures.new("LWF_Attendee_Skeleton")
rig = bpy.data.objects.new("LWF_Attendee_Rig", arm_data); bpy.context.scene.collection.objects.link(rig)
bpy.context.view_layer.objects.active = rig; bpy.ops.object.mode_set(mode='EDIT')
for name, (h, t, parent) in BONES.items():
    b = arm_data.edit_bones.new(name); b.head, b.tail = h, t; b.roll = 0.0
for name, (h, t, parent) in BONES.items():
    if parent: arm_data.edit_bones[name].parent = arm_data.edit_bones[parent]
bpy.ops.object.mode_set(mode='OBJECT')

# ---------------------------------------------------------------- weights
def smooth(t): t = max(0.0, min(1.0, t)); return t * t * (3 - 2 * t)
def along(p, a, b):
    ab = b - a; return (p - a).dot(ab) / ab.length
def chain_weights(p, joints, names, band):
    """blend between consecutive segments of a chain at each inner joint over +-band metres along the chain"""
    w = {}
    d1 = along(p, joints[0], joints[1]); L1 = (joints[1] - joints[0]).length
    if len(joints) == 2: return {names[0]: 1.0}
    t = smooth((d1 - (L1 - band)) / (2 * band))         # 0 on the first segment, 1 past its end
    if len(joints) == 3:
        return {names[0]: 1 - t, names[1]: t}
    d2 = along(p, joints[1], joints[2]); L2 = (joints[2] - joints[1]).length
    u = smooth((d2 - (L2 - band * 0.5)) / band)
    return {names[0]: 1 - t, names[1]: t * (1 - u), names[2]: t * u}

W = []
for i, v in enumerate(me.vertices):
    p, part = V(v.co), vpart[i]
    sx = -1 if p.x < 0 else 1; side = "Left" if sx < 0 else "Right"
    if part in ("Head", "Nose", "Eyes", "Mouth", "Ears"):
        if part == "Head" and p.z < chin + 0.01:
            t = smooth((p.z - (chin - 0.03)) / 0.04)
            b = smooth((p.z - (neck_base - 0.02)) / 0.05)
            w = {"Head": t, "Neck": (1 - t) * b, "Chest": (1 - t) * (1 - b)}
        else: w = {"Head": 1.0}
    elif part in ("Tee", "Patch") and (part == "Patch" or i in torso_verts):
        z = p.z
        a = smooth((z - (hipz + 0.06)) / 0.10); c = smooth((z - (1.10 * S * K)) / 0.10)
        w = {"Hips": 1 - a, "Spine": a * (1 - c), "Chest": a * c}
    elif part in ("Tee", "SleeveLining"):              # sleeves follow the upper arm, easing in at the shoulder
        t = smooth((along(p, sh[sx], el[sx]) + 0.01) / 0.05)
        w = {f"{side}UpperArm": t, "Chest": 1 - t}
    elif part == "Arms":
        w = chain_weights(p, [sh[sx], el[sx], wr[sx], hand_end[sx]], [f"{side}UpperArm", f"{side}LowerArm", f"{side}Hand"], 0.045)
    elif part == "Trousers":
        if p.z > hipz + 0.02 or abs(p.x) < 0.02:
            w = {"Hips": 1.0}
        else:
            top = smooth((hip[sx].z + 0.0 - p.z) / 0.08)       # 0 at the hip line, 1 a little below
            leg = chain_weights(p, [hip[sx], knee[sx], ankle[sx]], [f"{side}UpperLeg", f"{side}LowerLeg"], 0.06)
            w = {k_: v_ * top for k_, v_ in leg.items()}; w["Hips"] = 1 - top
    elif part == "Shoes":
        t = smooth((p.z - 0.07) / 0.06)
        w = {f"{side}Foot": 1 - t * 0.6, f"{side}LowerLeg": t * 0.6}
    else:
        w = {"Hips": 1.0}
    W.append(w)
body.vertex_groups.clear()
for name in BONES: body.vertex_groups.new(name=name)
for i, w in enumerate(W):
    tot = sum(w.values()) or 1
    for b, x in w.items():
        if x > 1e-4: body.vertex_groups[b].add([i], x / tot, 'REPLACE')
body.parent = rig
mod = body.modifiers.new("Armature", 'ARMATURE'); mod.object = rig

# ---------------------------------------------------------------- animation helpers
pb = rig.pose.bones
for b in pb: b.rotation_mode = 'QUATERNION'
def rest3(name): return arm_data.bones[name].matrix_local.to_3x3()
def rot_world(name, axis, deg):
    """local quaternion for a rotation about a world (armature) axis through the bone's rest frame"""
    ax = (rest3(name).inverted() @ V(axis)).normalized()
    return Quaternion(ax, math.radians(deg))
def key(name, q, f, loc=None):
    pb[name].rotation_quaternion = q; pb[name].keyframe_insert("rotation_quaternion", frame=f)
    if loc is not None:
        pb[name].location = rest3(name).inverted() @ V(loc); pb[name].keyframe_insert("location", frame=f)
X, Y, Z = (1, 0, 0), (0, 1, 0), (0, 0, 1)
def combine(*qs):
    q = Quaternion()
    for x in qs: q = q @ x
    return q

def make_action(name, frames, fn):
    act = bpy.data.actions.new(name); rig.animation_data_create(); rig.animation_data.action = act
    for b in pb: b.rotation_quaternion = Quaternion(); b.location = V()
    for f in range(frames): fn(f, 2 * math.pi * f / (frames - 1))
    for fc in act.fcurves:
        for kp in fc.keyframe_points: kp.interpolation = 'LINEAR'
    act.use_fake_user = True
    tr = rig.animation_data.nla_tracks.new(); tr.name = name; tr.strips.new(name, 1, act); tr.mute = True
    rig.animation_data.action = None
    return act

# ---- walk: foot-planted IK. During stance each foot's heel and ball stay fixed on the ground (heel-strike rocker,
# flat, toe-off rocker about the ball) while the root moves forward at SPEED, so a planted foot does not slide.
CYCLE = (WALK_N - 1) / FPS                          # 1.125 s for two steps
DUTY = 0.62                                         # stance share of each leg's cycle
STEP_WANT = 0.58 if not F else 0.53                 # metres per step (half a cycle)
HEEL_PH, TOE_PH = 0.12, 0.70                        # stance phases where the heel rocker ends and the toe rocker starts
HEEL_UP, TOE_DOWN = 14.0, 32.0                      # foot pitch at heel strike / at toe-off (degrees)
LIFT = 0.075                                        # swing clearance (m)
BOB0, BOBA, LIVE, ARM, ELBOW, LEAN = -0.040, 0.012, 1.0, 1.0, 14.0, 3.0   # pelvis height/bounce, liveliness, arm swing, elbow, lean


def yz(v): return V((v.y, v.z))


LEGS = {}
for _sx, _side in ((-1, "Left"), (1, "Right")):
    _h, _k, _a = hip[_sx], knee[_sx], ankle[_sx]
    LEGS[_side] = dict(hip=_h, L1=(yz(_k) - yz(_h)).length, L2=(yz(_a) - yz(_k)).length,
                       a1r=math.atan2(_k.y - _h.y, -(_k.z - _h.z)), a2r=math.atan2(_a.y - _k.y, -(_a.z - _k.z)),
                       ankz=_a.z, ankx=_a.x, heel=-0.085 * K, ball=0.140 * K)


def rot2(v, deg):
    """rotate a (y, z) vector by deg; positive raises the toe of a foot"""
    c, s_ = math.cos(math.radians(deg)), math.sin(math.radians(deg))
    return V((v.x * c - v.y * s_, v.x * s_ + v.y * c))


def stance_ankle(leg, u):
    """ankle (y, z) and foot pitch at stance phase u in [0, 1]; ground frame with the heel landing at y = 0"""
    hz = leg["ankz"]
    heel_to_ank = V((-leg["heel"], hz)); ball_to_ank = V((-leg["ball"], hz))
    if u < HEEL_PH:
        pitch = HEEL_UP * (1 - u / HEEL_PH)
        return rot2(heel_to_ank, pitch), pitch
    ballw = V((leg["ball"] - leg["heel"], 0))
    if u < TOE_PH:
        return ballw + ball_to_ank, 0.0
    pitch = -TOE_DOWN * ((u - TOE_PH) / (1 - TOE_PH)) ** 1.2
    return ballw + rot2(ball_to_ank, pitch), pitch


def hips_motion(ph):
    """bob, sway, yaw, roll at cycle phase ph (left heel strike at ph = 0)"""
    t = 2 * math.pi * ph
    bob = BOB0 + BOBA * math.cos(2 * math.pi * 2 * (ph - DUTY / 2))    # soft knees; highest at mid-stance
    return bob, 0.012 * LIVE * math.sin(t + 0.6), 4 * LIVE * math.sin(t), -2.5 * math.sin(t)


def leg_pose(side, lp, stride):
    """thigh, shin and foot world angles (degrees from rest) and reach fraction at this leg's phase lp"""
    leg = LEGS[side]; v = stride / CYCLE
    ph = (lp + (0.0 if side == "Left" else 0.5)) % 1.0
    bob = hips_motion(ph)[0]
    hip_z = leg["hip"].z + bob
    foot_len = leg["ball"] - leg["heel"]

    def hip_y(u):                                   # hip over the foot's middle at mid-stance, moving at v
        return v * CYCLE * DUTY * (u - 0.5) + foot_len * 0.45

    def anc(u):
        p, pitch = stance_ankle(leg, u)
        return V((p.x - hip_y(u), p.y)), pitch      # ankle relative to the hip's ground point

    if lp < DUTY:
        a, pitch = anc(lp / DUTY)
    else:
        w = (lp - DUTY) / (1 - DUTY); e = w * w * (3 - 2 * w)
        a0, p0 = anc(1.0); a1, p1 = anc(0.0)
        a1 = a1 + V((v * CYCLE, 0)) * 0             # periodic in the hip frame
        a = a0.lerp(a1, e) + V((0, LIFT * math.sin(math.pi * w) ** 1.3))
        pitch = p0 + (p1 - p0) * e - 18 * math.sin(math.pi * w) * (1 - w)
    d = V((a.x, a.y - hip_z))                       # ankle relative to the hip joint
    D = d.length; Lsum = leg["L1"] + leg["L2"]; reach = D / Lsum
    if D > Lsum * 0.995:
        d = d * (Lsum * 0.995 / D); D = d.length
    alpha = math.atan2(d.x, -d.y)
    beta = math.acos(max(-1.0, min(1.0, (leg["L1"] ** 2 + D * D - leg["L2"] ** 2) / (2 * leg["L1"] * D))))
    phi1 = alpha + beta                             # knee bends forward
    kp = V((leg["L1"] * math.sin(phi1), -leg["L1"] * math.cos(phi1)))
    phi2 = math.atan2(d.x - kp.x, -(d.y - kp.y))
    return math.degrees(phi1 - leg["a1r"]), math.degrees(phi2 - leg["a2r"]), pitch, reach


def stride_fits(stride):
    return max(leg_pose(side, i / 60, stride)[3] for side in LEGS for i in range(60))


STRIDE = 2 * STEP_WANT
STRIDE_WANT = STRIDE
while stride_fits(STRIDE) > 0.99 and STRIDE > 0.6:
    STRIDE -= 0.01
SPEED = STRIDE / CYCLE


def world_q(name, Mw):
    R = rest3(name); return (R.inverted() @ Mw @ R).to_quaternion()


def RX(deg): return Matrix.Rotation(math.radians(deg), 3, 'X')


def walk(f, t):
    fr = f + 1; ph = f / (WALK_N - 1)
    bob, sway, yaw, roll = hips_motion(ph)
    Rh = Matrix.Rotation(math.radians(yaw), 3, 'Z') @ Matrix.Rotation(math.radians(roll), 3, 'Y')
    key("Hips", world_q("Hips", Rh), fr, loc=(sway, 0, bob))
    for sx, side, off in ((-1, "Left", 0.0), (1, "Right", 0.5)):
        lp = (ph + off) % 1.0
        th, shn, pitch, _ = leg_pose(side, lp, STRIDE)
        key(f"{side}UpperLeg", world_q(f"{side}UpperLeg", Rh.inverted() @ RX(th)), fr)
        key(f"{side}LowerLeg", world_q(f"{side}LowerLeg", RX(shn - th)), fr)
        key(f"{side}Foot", world_q(f"{side}Foot", RX(pitch - shn)), fr)
        armph = 2 * math.pi * (lp - DUTY / 2)          # arm forward while its own leg trails behind
        arm = ARM * (19.0 if not F else 17.0) * math.sin(armph)
        key(f"{side}UpperArm", combine(rot_world(f"{side}UpperArm", X, arm), rot_world(f"{side}UpperArm", Y, sx * -4)), fr)
        key(f"{side}LowerArm", rot_world(f"{side}LowerArm", X, ELBOW + 10 * ARM * max(0.0, math.sin(armph))), fr)
        key(f"{side}Hand", Quaternion(), fr)
    key("Spine", rot_world("Spine", X, LEAN), fr)
    key("Chest", combine(rot_world("Chest", Z, -2 * yaw), rot_world("Chest", Y, -0.6 * roll)), fr)
    key("Neck", rot_world("Neck", Z, 0.5 * yaw), fr)
    key("Head", combine(rot_world("Head", Y, -0.5 * roll), rot_world("Head", X, -2)), fr)

def idle(f, t):
    fr = f + 1
    br = math.sin(t)
    key("Hips", rot_world("Hips", Y, 1.2 * math.sin(t * 0.5) if False else 1.0 * math.sin(t)), fr, loc=(0.006 * math.sin(t), 0, 0.002 * br))
    key("Spine", rot_world("Spine", X, 0.8 * br), fr)
    key("Chest", rot_world("Chest", X, -1.5 * br), fr)
    key("Neck", Quaternion(), fr); key("Head", rot_world("Head", X, 0.8 * br), fr)
    for sx, side in ((-1, "Left"), (1, "Right")):
        key(f"{side}UpperArm", rot_world(f"{side}UpperArm", Y, sx * -(2 + 0.8 * br)), fr)
        key(f"{side}LowerArm", rot_world(f"{side}LowerArm", X, 6), fr)
        key(f"{side}Hand", Quaternion(), fr)
        key(f"{side}UpperLeg", rot_world(f"{side}UpperLeg", Y, -1.0 * math.sin(t)), fr)
        key(f"{side}LowerLeg", Quaternion(), fr); key(f"{side}Foot", rot_world(f"{side}Foot", Y, 1.0 * math.sin(t)), fr)

make_action("walk", WALK_N, walk)
make_action("idle", IDLE_N, idle)
# ---------------------------------------------------------------- carrying and drinking (right arm solved to a cup frame)
# Cup frames reuse the pose bodies' anchors (attendee_poses_v6_manifest.json): drink_hold for carrying (upright), drinking
# beer / soft for the sip. The hand grips the cup as the pose generator's cup_hand does; the cup socket
# LWF_RightHand_Cup rides on the RightHand bone, so whatever is attached there follows the hand.
MAN = json.load(open("C:/Projects/festival-tycoon/assets/source/characters/attendee-v6-draft/poses/attendee_poses_v6_manifest.json"))


def anchor(state, product, key_):
    v = next(x for x in MAN["variants"][SEX] if x["state"] == state and (x["product"] == product))
    a = v["attachments"][key_]; p = a["position"]; r = a["rotation_degrees"]
    return Matrix.Translation(V((p[0], -p[2], p[1]))) @ Matrix.Rotation(math.radians(r[0]), 4, 'X')


C_HOLD = anchor("drink_hold", None, "beer")
C_BEER = anchor("drinking_beer", "beer", "beer") if any(x["state"] == "drinking_beer" for x in MAN["variants"][SEX]) else None
if C_BEER is None:
    C_BEER = next(Matrix.Translation(V((a["position"][0], -a["position"][2], a["position"][1]))) @ Matrix.Rotation(math.radians(a["rotation_degrees"][0]), 4, 'X')
                  for x in MAN["variants"][SEX] if x["state"] == "drinking" and x["product"] == "beer" for a in [x["attachments"]["beer"]])
C_SOFT = next(Matrix.Translation(V((a["position"][0], -a["position"][2], a["position"][1]))) @ Matrix.Rotation(math.radians(a["rotation_degrees"][0]), 4, 'X')
              for x in MAN["variants"][SEX] if x["state"] == "drinking" and x["product"] == "soft" for a in [x["attachments"]["soft"]])

# cup radius at the grip (soft cup is the wider; one grip fits both, as in the pose generator)
_before = set(bpy.data.objects)
bpy.ops.import_scene.gltf(filepath="C:/Projects/festival-tycoon/assets/runtime/props/lwf_soft_drink_cup_v1.glb")
_cup = [o for o in bpy.data.objects if o not in _before]
_pts = [o.matrix_world @ v.co for o in _cup if o.type == 'MESH' for v in o.data.vertices]
RC = max(math.hypot(p.x, p.y) for p in _pts if abs(p.z) < 0.045) + 0.002
for o in _cup: bpy.data.objects.remove(o)
GT = 0.015

# hand bone frame in the cup frame (fixed grip): wrist behind-outside the cup, fingers wrapping towards the front
def _P(phi, r, hh): return V((r * math.cos(math.radians(phi)), r * math.sin(math.radians(phi)), hh))
_wrist = _P(-68, RC + 0.036, -0.014)
_grip = _P(-12, RC + GT + 0.001, -0.004)
_hand_rest = arm_data.bones["RightHand"].matrix_local.to_3x3()
_ynew = (_grip - _wrist).normalized()
_R = _hand_rest.col[1].rotation_difference(_ynew).to_matrix() @ _hand_rest
HAND_IN_CUP = Matrix.Translation(_wrist) @ _R.to_4x4()          # RightHand bone (armature space) relative to the cup


def chest_delta():
    bpy.context.view_layer.update()
    return pb["Chest"].matrix @ arm_data.bones["Chest"].matrix_local.inverted()


def set_bone_dir(name, target):
    """rotate a bone (local rotation reset first) so it points from its posed head to target"""
    b = pb[name]; b.rotation_quaternion = Quaternion(); b.location = V()
    bpy.context.view_layer.update()
    M = b.matrix.copy(); head = M.translation.copy()
    q = M.col[1].xyz.normalized().rotation_difference((target - head).normalized())
    b.matrix = Matrix.Translation(head) @ q.to_matrix().to_4x4() @ M.to_3x3().to_4x4()
    bpy.context.view_layer.update()


def right_arm_to(fr, C, pole):
    """solve the right arm so the cup socket lands on frame C (armature space)"""
    H = C @ HAND_IN_CUP; W = H.translation.copy()
    bpy.context.view_layer.update()
    S = pb["RightUpperArm"].head.copy() if False else (pb["RightUpperArm"].matrix.translation.copy())
    Lu = arm_data.bones["RightUpperArm"].length; Lf = arm_data.bones["RightLowerArm"].length
    d = (W - S).length
    if d > (Lu + Lf) * 0.999: W = S + (W - S).normalized() * (Lu + Lf) * 0.999; d = (W - S).length
    a = (Lu * Lu - Lf * Lf + d * d) / (2 * d); h = math.sqrt(max(Lu * Lu - a * a, 0))
    ax = (W - S).normalized(); p = V(pole) - ax * V(pole).dot(ax)
    E = S + ax * a + p.normalized() * h
    set_bone_dir("RightUpperArm", E)
    set_bone_dir("RightLowerArm", W)
    b = pb["RightHand"]; b.rotation_quaternion = Quaternion(); b.location = V(); bpy.context.view_layer.update()
    b.matrix = Matrix.Translation(b.matrix.translation) @ H.to_3x3().to_4x4()
    bpy.context.view_layer.update()
    for n in ("RightUpperArm", "RightLowerArm", "RightHand"):
        pb[n].keyframe_insert("rotation_quaternion", frame=fr); pb[n].keyframe_insert("location", frame=fr)


def interp(A, B, t):
    loc = A.translation.lerp(B.translation, t)
    rot = A.to_quaternion().slerp(B.to_quaternion(), t)
    return Matrix.Translation(loc) @ rot.to_matrix().to_4x4()


HOLD_POLE = (0.35, -0.55, -1.0)
DRINK_POLE = (1.0, 0.0, -0.6)


def walk_carry(f, t):
    walk(f, t)
    swing = 0.012 * math.sin(2 * math.pi * f / (WALK_N - 1) - 1.2)
    right_arm_to(f + 1, chest_delta() @ Matrix.Translation(V((0, swing, 0.006 * math.cos(4 * math.pi * f / (WALK_N - 1))))) @ C_HOLD, HOLD_POLE)


def idle_carry(f, t):
    idle(f, t)
    right_arm_to(f + 1, chest_delta() @ Matrix.Translation(V((0, 0, 0.003 * math.sin(t)))) @ C_HOLD, HOLD_POLE)


DRINK_N = 67                                                     # 66 intervals = 2.75 s
def _ss(x): x = max(0.0, min(1.0, x)); return x * x * (3 - 2 * x)
def drink_curve(f):
    """0 = holding, 1 = at the mouth: hold 0.35 s, raise 0.6 s, sip 1.0 s, lower 0.6 s, hold"""
    s = f / 24.0
    return _ss((s - 0.35) / 0.6) * (1 - _ss((s - 1.95) / 0.6))


def make_drink(C_mouth, pole_mouth):
    def fn(f, t):
        idle(f, 2 * math.pi * f / (DRINK_N - 1))
        u = drink_curve(f)
        key("Head", rot_world("Head", X, 0.8 * math.sin(t) - 7 * u), f + 1)   # tip the head back to sip
        key("Neck", rot_world("Neck", X, -3 * u), f + 1)
        C = interp(C_HOLD, C_mouth, u)
        if 0.95 < u: C = C @ Matrix.Rotation(math.radians(4 * math.sin(2 * math.pi * f / 24)), 4, 'X')    # small sips
        pole = V(HOLD_POLE).lerp(V(pole_mouth), u)
        right_arm_to(f + 1, chest_delta() @ C, pole)
    return fn


def carry_litter(f, t):
    walk(f, t)
    sh_r = pb["RightUpperArm"].matrix.translation
    wr0 = wr[1]
    C = Matrix.Translation(V((wr0.x - 0.02, wr0.y + 0.10, wr0.z + 0.05)) + V((0, 0.010 * math.sin(2 * math.pi * f / (WALK_N - 1) - 1.2), 0)))
    C = C @ Matrix.Rotation(math.radians(-90), 4, 'X')            # hand hanging forward: socket points along the hand
    right_arm_to(f + 1, chest_delta() @ C, (0.6, -0.4, -1.0))

make_action("walk_carry", WALK_N, walk_carry)
make_action("idle_carry", IDLE_N, idle_carry)
make_action("drink", DRINK_N, make_drink(C_BEER, DRINK_POLE))
make_action("drink_soft", DRINK_N, make_drink(C_SOFT, DRINK_POLE))
make_action("carry_litter", WALK_N, carry_litter)

# cup socket on the RightHand bone, placed while the rig holds the carry pose
rig.animation_data.action = bpy.data.actions["idle_carry"]; bpy.context.scene.frame_set(1); bpy.context.view_layer.update()
CUP_TARGET = chest_delta() @ C_HOLD
socket = bpy.data.objects.new("LWF_RightHand_Cup", None); bpy.context.scene.collection.objects.link(socket)
socket.empty_display_size = 0.05
socket.parent = rig; socket.parent_type = 'BONE'; socket.parent_bone = "RightHand"
bpy.context.view_layer.update(); socket.matrix_world = rig.matrix_world @ CUP_TARGET
bpy.context.view_layer.update()
rig.animation_data.action = None
for b in pb: b.rotation_quaternion = Quaternion(); b.location = V()

# ---------------------------------------------------------------- stride measurement (left foot's ground contact travel)
def measure_slide(action):
    # measure: with the root moving at SPEED, how far does each planted contact point (heel, then flat, then ball) move?
    sc = bpy.context.scene; sc.render.fps = FPS
    rig.animation_data.action = bpy.data.actions[action]
    slide = 0.0
    for side, off in (("Left", 0.0), ("Right", 0.5)):
        fb = pb[f"{side}Foot"]; inv = fb.bone.matrix_local.inverted()
        lx = LEGS[side]["ankx"]
        base = {}
        for f in range(WALK_N - 1):
            lp = (f / (WALK_N - 1) + off) % 1.0
            if lp >= DUTY * 0.98:
                continue
            sc.frame_set(f + 1)
            m = rig.matrix_world @ fb.matrix
            heelp = m @ (inv @ V((lx, LEGS[side]["heel"], 0.0)))
            ballp = m @ (inv @ V((lx, LEGS[side]["ball"], 0.0)))
            u = lp / DUTY
            phase = 0 if u < HEEL_PH else (1 if u < TOE_PH else 2)
            pt = heelp if phase == 0 else (ballp if phase == 2 else (heelp + ballp) / 2)
            y = pt.y + SPEED * (lp * CYCLE)             # world y once the root moves forward
            key_ = (phase,)
            base.setdefault(key_, y)
            slide = max(slide, abs(y - base[key_]))
    return slide
slide = measure_slide("walk")

# ---------------------------------------------------------------- brisk walk: same IK, faster and longer striding
WALK_GAIT = dict(WALK_N=WALK_N, CYCLE=CYCLE, DUTY=DUTY, HEEL_PH=HEEL_PH, TOE_PH=TOE_PH, HEEL_UP=HEEL_UP, TOE_DOWN=TOE_DOWN, LIFT=LIFT,
                 BOB0=BOB0, BOBA=BOBA, LIVE=LIVE, ARM=ARM, ELBOW=ELBOW, LEAN=LEAN, STRIDE=STRIDE, SPEED=SPEED)
BRISK_TARGET = 1.70
BRISK_N = 21                                        # 20 intervals = 0.833 s per two steps (144 steps a minute)
globals().update(WALK_N=BRISK_N, CYCLE=(BRISK_N - 1) / FPS, DUTY=0.56, HEEL_PH=0.13, TOE_PH=0.62, HEEL_UP=18.0, TOE_DOWN=38.0,
                 LIFT=0.095, BOBA=0.018, LIVE=1.4, ARM=1.35, ELBOW=22.0, LEAN=6.0)
_want = BRISK_TARGET * CYCLE
BOB0 = -0.040
while stride_fits(_want) > 0.99 and BOB0 > -0.11: BOB0 -= 0.005
STRIDE = _want
while stride_fits(STRIDE) > 0.99 and STRIDE > 0.8: STRIDE -= 0.01
SPEED = STRIDE / CYCLE
make_action("walk_brisk", BRISK_N, walk)
make_action("walk_brisk_carry", BRISK_N, walk_carry)
brisk_slide = measure_slide("walk_brisk")
BRISK = dict(step_length_m=round(STRIDE / 2, 3), metres_per_cycle=round(STRIDE, 3), cycle_seconds=round(CYCLE, 4),
             walk_speed_m_per_s=round(SPEED, 3), planted_foot_max_slide_mm=round(brisk_slide * 1000, 1), stance_share=DUTY,
             pelvis_drop_m=round(-BOB0, 3), frames=BRISK_N)
globals().update(WALK_GAIT)
step = STRIDE / 2; speed = SPEED
rig.animation_data.action = None; bpy.context.scene.frame_set(1)
for b in pb: b.rotation_quaternion = Quaternion(); b.location = V()

# ---------------------------------------------------------------- export
bpy.ops.object.select_all(action='DESELECT'); rig.select_set(True); body.select_set(True); socket.select_set(True)
bpy.context.view_layer.objects.active = rig
path = os.path.join(OUT, NAME + ".glb")
bpy.ops.export_scene.gltf(filepath=path, export_format='GLB', use_selection=True, export_yup=True, export_skins=True,
                          export_animations=True, export_animation_mode='NLA_TRACKS', export_force_sampling=True,
                          export_def_bones=False, export_frame_range=False)
bpy.ops.wm.save_as_mainfile(filepath=os.path.join(OUT, NAME + ".blend"))
def godot(v): return [round(v.x, 4), round(v.z, 4), round(-v.y, 4)]
rep = dict(file=NAME + ".glb", sex=SEX, triangles=sum(len(p.vertices) - 2 for p in me.polygons), vertices=len(me.vertices),
           bones=list(BONES), cup_socket="LWF_RightHand_Cup (child of RightHand)", animations={"walk_carry": "as walk, right hand holding a cup at drink_hold", "idle_carry": "as idle, right hand holding a cup", "drink": f"{DRINK_N} frames (2.75 s): beer sip, cup tilts 55 deg at the lips", "drink_soft": f"{DRINK_N} frames: soft-drink sip, 25 deg", "carry_litter": "as walk, right hand low carrying litter", "walk_brisk": f"{BRISK_N} frames: brisk walk, see stride_brisk", "walk_brisk_carry": "walk_brisk with the cup held (as walk_carry)", "walk": f"{WALK_N} frames at {FPS} fps ({CYCLE:.3f} s, two steps), loops", "idle": f"{IDLE_N} frames at {FPS} fps (2.0 s), loops"},
           stride_brisk=BRISK,
           stride=dict(step_length_m=round(step, 3), metres_per_cycle=round(STRIDE, 3), cycle_seconds=round(CYCLE, 4), walk_speed_m_per_s=round(speed, 3),
                       planted_foot_max_slide_mm=round(slide * 1000, 1), stance_share=DUTY,
                       note="move the guest at metres_per_cycle per 1.0 s cycle (scale playback speed by actual speed / walk_speed_m_per_s)"),
           attach=dict(head_bone="Head", head_bone_rest_godot=godot(BONES["Head"][0]), right_hand_bone="RightHand",
                       right_hand_rest_godot=godot(BONES["RightHand"][0])),
           sha256=hashlib.sha256(open(path, "rb").read()).hexdigest())
json.dump(rep, open(os.path.join(OUT, NAME + ".json"), "w"), indent=1)
print("RIGGED", json.dumps(rep))
