# usage: blender -b --python build_performer_v6.py -- <female|male> <out_dir> <relaxed|guitarist|bassist|drummer>
# Performer bodies and playing kits on the v6 attendee, generated by the designer's own
# attendee-v6-draft/build_attendee.py so arms, sleeves and hands match the guest bodies exactly.
#   relaxed   -> lwf_performer_<sex>_body_v2.glb (BodyCore + IdleLeftArm + IdleRightArm; sleeves belong to the arms)
#   <role>    -> lwf_<role>_<sex>_kit_v2.glb (instrument, refitted strap, IK playing arms, sticks, one merged loop)
# Instruments, drum hardware, sticks and the loop keyframes come unchanged from role-assets-v1.
import bpy, bmesh, sys, os, json, math, hashlib
from mathutils import Vector, Matrix
from mathutils.bvhtree import BVHTree
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from refit_common import ROOT, append, islands, Transfer, depth

SEX, OUTDIR, MODE = sys.argv[sys.argv.index("--") + 1:][:3]
V3 = Vector
V1 = ROOT + "role-assets-v1/"
V6 = ROOT + "attendee-v6-draft/"
ARM_NAME = {"guitarist": "Guitarist", "bassist": "Bassist", "drummer": "Drummer"}
INSTRUMENT = {"guitarist": "LWF_Guitarist_AcousticGuitar", "bassist": "LWF_Bassist_SolidBass"}
HAND_CENTRE = 0.046      # v6 mitten centroid distance from the wrist along the finger axis
CLEAR = 0.012            # minimum gap between the v6 body and instrument / drum hardware
REACH_USE = 0.96         # fraction of full arm length the IK may use (keeps a visible elbow bend)
# v1 instruments float ~0.3 m ahead of the body on stretched arms. v6 arms are true length, so the
# instrument (with its strap, sticks and hand targets) moves in toward the body until both hands reach.
# None = search per body; the stage drum hardware is shared by both bodies, so it uses one fixed move.
SHIFTS = {"guitarist": None, "bassist": None, "drummer": (0, -0.085, 0.02)}  # drummer: female requirement, shared
# finger-direction bias per hand: fret hand fingers over the neck, strum/pluck hand down across strings
# elbow pole per hand: the strum/pluck elbow sits out and forward so the forearm rests over the
# instrument's upper edge instead of passing through its body
POLE = {"guitarist": {-1: (-0.7, -0.5, -1.0), 1: (1.0, 0.9, 0.2)}, "bassist": {-1: (-0.7, -0.5, -1.0), 1: (1.0, 0.9, 0.2)},
        "drummer": {-1: (-0.7, -0.5, -1.0), 1: (0.7, -0.5, -1.0)}}
BIAS = {"guitarist": {-1: (0, 0, 0.8), 1: (0, 0, -0.9)}, "bassist": {-1: (0, 0, 0.8), 1: (0, 0, -0.9)},
        "drummer": {-1: (0, 0.4, -0.3), 1: (0, 0.4, -0.3)}}


def inside(tree, p, direction=V3((0.3713, 0.5571, 0.7428))):
    """ray parity test against a closed mesh"""
    hits, o = 0, p.copy()
    while True:
        loc, n, i, d = tree.ray_cast(o, direction)
        if loc is None: return hits % 2 == 1
        hits += 1; o = loc + direction * 1e-5


def mesh_islands(ob):
    bm = bmesh.new(); bm.from_mesh(ob.data); bm.faces.ensure_lookup_table()
    return [[ob.matrix_world @ v.co for v in {v for f in isl for v in f.verts}] for isl in islands(bm, bm.faces)]


# ---------------------------------------------------------------- stage drum hardware: same move as the drummer kit
if MODE == "hardware":
    bpy.ops.wm.read_factory_settings(use_empty=True)
    hw = append(V1 + "lwf_drum_hardware_only_v1.blend", lambda n: n.startswith("LWF_"))
    for o in hw: o.location += V3(SHIFTS["drummer"])
    path = os.path.join(OUTDIR, "lwf_drum_hardware_only_v2")
    bpy.ops.wm.save_as_mainfile(filepath=path + ".blend")
    bpy.ops.object.select_all(action='DESELECT')
    for o in hw: o.select_set(True)
    bpy.context.view_layer.objects.active = hw[0]
    bpy.ops.export_scene.gltf(filepath=path + ".glb", export_format='GLB', use_selection=True, export_yup=True,
                              export_animations=False)
    report = dict(mode=MODE, file="lwf_drum_hardware_only_v2.glb", nodes=[o.name for o in hw],
                  shift_mm=[x * 1000 for x in SHIFTS["drummer"]],
                  triangles=sum(len(p.vertices) - 2 for o in hw for p in o.data.polygons),
                  sha256=hashlib.sha256(open(path + ".glb", "rb").read()).hexdigest())
    json.dump(report, open(path + ".json", "w"), indent=1)
    print("PERFORMER", json.dumps(report))
    raise SystemExit(0)

# ---------------------------------------------------------------- old kit analysis (before the generator resets the scene)
PLAY, OLD_KEYS, STATE = {}, {}, {"shift": V3(), "slide": 0.0}
if MODE != "relaxed":
    bpy.ops.wm.read_factory_settings(use_empty=True)
    kit = append(V1 + f"lwf_{MODE}_{SEX}_kit_v1.blend", lambda n: n.startswith("LWF_"))
    body6 = append(V6 + f"{SEX}-attendee-v6.blend", lambda n: True)[0]
    dg = bpy.context.evaluated_depsgraph_get()
    tree6 = BVHTree.FromObject(body6, dg)
    BODY_PTS = [body6.matrix_world @ v.co for v in body6.data.vertices]
    fixed = [o for o in kit if o.name in (INSTRUMENT.get(MODE), "LWF_Drummer_DrumShells", "LWF_Drummer_CymbalsHardware")]
    FIXED_PTS, polys = [], []
    for o in fixed:
        base = len(FIXED_PTS)
        FIXED_PTS += [o.matrix_world @ v.co for v in o.data.vertices]
        polys += [[base + i for i in p.vertices] for p in o.data.polygons]
    fixed_tree = BVHTree.FromPolygons(FIXED_PTS, polys)

    def clearance(s):
        """unsigned surface gap, measured both ways so large faces cannot hide a crossing"""
        return min(min(tree6.find_nearest(p + s)[3] for p in FIXED_PTS),
                   min(fixed_tree.find_nearest(p - s)[3] for p in BODY_PTS))

    for sx, side in ((-1, "Left"), (1, "Right")):
        arm = next(o for o in kit if o.name == f"LWF_{ARM_NAME[MODE]}_{side}PlayingArm")
        pivot = arm.matrix_world.translation.copy()
        hand = sorted(mesh_islands(arm), key=len)[0]
        hc = sum(hand, V3()) / len(hand)
        PLAY[sx] = dict(centre=hc, bias=V3(BIAS[MODE][sx]), pole=V3(POLE[MODE][sx]))
        if arm.animation_data and arm.animation_data.action:
            fc = arm.animation_data.action.fcurves[0]
            OLD_KEYS[sx] = dict(index=fc.array_index, keys=[(k.co[0], k.co[1]) for k in fc.keyframe_points],
                                lever=(hc - pivot).length)

    # neck axis (towards the headstock); the fret hand may slide down it towards the body
    NECK = None
    if MODE in INSTRUMENT:
        import numpy as np
        inst_pts = [p for o in fixed for p in (o.matrix_world @ v.co for v in o.data.vertices)]
        c = sum(inst_pts, V3()) / len(inst_pts)
        cov = np.cov(np.array([tuple(p - c) for p in inst_pts]).T)
        NECK = V3(np.linalg.eigh(cov)[1][:, 2])
        if NECK.x > 0: NECK = -NECK

    def target(sx, s, u):
        t = PLAY[sx]["centre"] + s
        return t - NECK * u if (sx == -1 and NECK is not None) else t

    def choose_shift(shoulders, reaches):
        """smallest instrument move (in towards the body, then up) plus fret-hand slide that lets both hands reach"""
        if SHIFTS[MODE] is not None: return V3(SHIFTS[MODE]), 0.0
        slack = lambda s, u: min(REACH_USE * reaches[sx] - ((target(sx, s, u) - shoulders[sx]).length - HAND_CENTRE)
                                 for sx in PLAY)
        best = None
        for dz in [0.02 * k for k in range(11)]:
            for u in ([0.025 * k for k in range(13)] if NECK is not None else [0.0]):
                for i in range(0, 61):
                    s = V3((0, -0.005 * i, dz))
                    if slack(s, u) < 0: continue
                    cost = s.length + 0.5 * u
                    if (best is None or cost < best[0]) and clearance(s) >= CLEAR: best = (cost, s, u)
                    break
        if best is None:
            raise RuntimeError(f"no instrument placement lets both v6 hands reach with {CLEAR * 1000:.0f} mm clearance")
        return best[1], best[2]

# ---------------------------------------------------------------- run the designer generator with a play pose
src = open(V6 + "build_attendee.py").read()
src = src.replace('assert POSE in ("relaxed",', 'assert POSE.startswith("play") or POSE in ("relaxed",')
hook = '''elif POSE == "play":
    shoulders = {sx: relaxed_joints(sx)[0] * K for sx in PLAY}
    reaches = {sx: sum((b - a).length for a, b in zip(relaxed_joints(sx), relaxed_joints(sx)[1:])) * K for sx in PLAY}
    SH, SLIDE = STATE["shift"], STATE["slide"] = CHOOSE(shoulders, reaches)
    for sx, spec in PLAY.items():
        centre = TARGET(sx, SH, SLIDE)
        d = ((centre - shoulders[sx]).normalized() + spec["bias"]).normalized()
        up = V3((0, 0, 1)) if abs(d.z) < 0.7 else V3((0, 1, 0))
        w = (up - d * up.dot(d)).normalized()
        W = centre - d * HAND_CENTRE
        print(f"REACH side={sx} need={(W - shoulders[sx]).length:.3f} have={reaches[sx]:.3f}")
        def build(bm, W=W, d=d, w=w):
            rings = [(0.000, 0.017, 0.026), (0.030, 0.021, 0.040), (0.065, 0.019, 0.038), (0.088, 0.011, 0.026)]
            gloft(bm, [R(W + d * a, t * hw, wd * hw, t=d) for a, t, wd in rings], 8, offset=0.5, ref=w)
            tb = W + d * 0.028 + w * 0.030 * hw
            td = (d * 0.8 + w * 0.6).normalized()
            gloft(bm, [R(tb, 0.010, 0.011, t=td), R(tb + td * 0.036, 0.008, 0.009, t=td)], 6, offset=0.5, ref=w)
        pose_arm(sx, build, W, spec["pole"])

# ---------------------------------------------------------------- legs / trousers'''
MARK = "# ---------------------------------------------------------------- legs / trousers"
src = src.replace("\n" + MARK, "\n" + hook, 1)
src = src[:src.index("# attachment sockets")]
PAL = V6 + f"{SEX}-attendee-v6.blend"
g = dict(__name__="__gen__", PLAY=PLAY, HAND_CENTRE=HAND_CENTRE, STATE=STATE,
         CHOOSE=choose_shift if MODE != "relaxed" else None, TARGET=target if MODE != "relaxed" else None)
sys.argv = [sys.argv[0], "--", SEX, os.path.join(OUTDIR, "_scratch.blend"), PAL, "play" if MODE != "relaxed" else "relaxed"]
exec(compile(src, V6 + "build_attendee.py", "exec"), g)
SHIFT = STATE["shift"]
if MODE != "relaxed":
    CLEARANCE = clearance(SHIFT)
    print("SHIFT_CHOSEN", tuple(round(x, 3) for x in SHIFT), "fret_slide", STATE["slide"], "clearance_mm", round(CLEARANCE * 1000, 1))
body = g["body"]; K = g["K"]; ARMS = g["ARMS"]; relaxed_joints = g["relaxed_joints"]

# ---------------------------------------------------------------- partition: sleeve + lining + arm + hand per side
bm = bmesh.new(); bm.from_mesh(body.data); bm.faces.ensure_lookup_table()
dl = bm.verts.layers.deform.active
gname = {vg.index: vg.name for vg in body.vertex_groups}
part = lambda f: gname[next(iter(f.verts[0][dl].keys()))]
limb = {-1: set(), 1: set()}


def seg_dist(p, a, b):
    ab = b - a; t = max(0.0, min(1.0, (p - a).dot(ab) / ab.dot(ab)))
    return (a + ab * t - p).length


chains = {sx: [j * K for j in ((ARMS[sx]["sh"], ARMS[sx]["el"], ARMS[sx]["wr"]) if ARMS[sx] else relaxed_joints(sx))]
          for sx in (-1, 1)}
tee = [isl for isl in islands(bm, bm.faces) if {part(f) for f in isl} == {"Tee"}]
torso = max(tee, key=len)
for isl in islands(bm, bm.faces):
    names = {part(f) for f in isl}
    if isl is torso or not names <= {"Arms", "SleeveLining", "Tee"}: continue
    if names == {"Tee"} and isl not in tee: continue
    c = sum((v.co for f in isl for v in f.verts), V3()) / sum(len(f.verts) for f in isl)
    # sleeves, linings, arm tubes, hands and thumbs belong to whichever arm chain they sit on
    sx = min((-1, 1), key=lambda k: min(seg_dist(c, a, b) for a, b in zip(chains[k], chains[k][1:])))
    limb[sx].update(f.index for f in isl)
bm.free()


def split(ob, faces_idx, name):
    """copy of ob keeping only the given polygon indices"""
    me = ob.data.copy(); new = bpy.data.objects.new(name, me)
    bpy.context.scene.collection.objects.link(new)
    b = bmesh.new(); b.from_mesh(me); b.faces.ensure_lookup_table()
    bmesh.ops.delete(b, geom=[f for f in b.faces if f.index not in faces_idx], context='FACES')
    b.to_mesh(me); b.free(); new.vertex_groups.clear()
    return new


allf = set(range(len(body.data.polygons)))
L, Rr = limb[-1], limb[1]
out_objs = []


def set_origin(ob, pivot):
    ob.data.transform(Matrix.Translation(-pivot)); ob.location = pivot


def export(path, objs, anim=False):
    bpy.ops.object.select_all(action='DESELECT')
    for o in objs: o.select_set(True)
    bpy.context.view_layer.objects.active = objs[0]
    kw = dict(export_animation_mode='ACTIVE_ACTIONS', export_force_sampling=False) if anim else {}
    bpy.ops.export_scene.gltf(filepath=path, export_format='GLB', use_selection=True, export_yup=True,
                              export_animations=anim, **kw)
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


tris = lambda objs: sum(len(p.vertices) - 2 for o in objs for p in o.data.polygons)
report = dict(sex=SEX, mode=MODE)
if MODE == "relaxed":
    old_mat = append(V1 + f"lwf_performer_{SEX}_body_v1.blend", lambda n: n == "LWF_Performer_BodyCore")[0]
    mat = old_mat.data.materials[0]; bpy.data.objects.remove(old_mat)
    core = split(body, allf - L - Rr, "LWF_Performer_BodyCore")
    la = split(body, L, "LWF_Performer_IdleLeftArm")
    ra = split(body, Rr, "LWF_Performer_IdleRightArm")
    for o in (core, la, ra): o.data.materials[0] = mat
    bpy.data.objects.remove(body)
    objs = [core, la, ra]
    name = f"lwf_performer_{SEX}_body_v2"
else:
    kit = append(V1 + f"lwf_{MODE}_{SEX}_kit_v1.blend", lambda n: n.startswith("LWF_") or n.startswith("REVIEW_Body"))
    by = {o.name: o for o in kit}
    for o in kit:
        if o.name.startswith("REVIEW_Body"): bpy.data.objects.remove(o)
    objs = []
    if MODE in INSTRUMENT:
        inst = by[INSTRUMENT[MODE]]; inst.location += SHIFT
        strap = by["LWF_Fitted_LeatherStrap"]
        # the strap was fitted to the v1 neutral body; refit it like a staff overlay, then follow the instrument
        oldb = append(V1 + f"lwf_steward_{SEX}_overlay_v1.blend", lambda n: "Attendee" in n)[0]
        tr = Transfer(oldb, body)
        before = [v.co.copy() for v in strap.data.vertices]
        off_body = [max(0.0, min(1.0, (depth(tr.oall, p) - 0.02) / 0.04)) for p in before]
        report["strap_fit"] = tr.fit(strap.data)
        # strap ends hang off the instrument, not the body: blend them onto the instrument move
        for v, p, w in zip(strap.data.vertices, before, off_body):
            v.co = v.co.lerp(p + SHIFT, w)
        bpy.data.objects.remove(oldb)
        objs += [inst, strap]
    core = split(body, allf - L - Rr, "REVIEW_v6_PlayCore")
    for sx, side, faces in ((-1, "Left", L), (1, "Right", Rr)):
        old = by[f"LWF_{ARM_NAME[MODE]}_{side}PlayingArm"]
        arm = split(body, faces, f"LWF_{ARM_NAME[MODE]}_{side}PlayingArm_new")
        arm.data.materials[0] = old.data.materials[0]
        pivot = relaxed_joints(sx)[0] * K
        set_origin(arm, pivot)
        bpy.context.view_layer.update()   # sticks re-parent against the moved pivot, not a stale matrix
        for stick in [c for c in old.children]:
            mw = Matrix.Translation(SHIFT) @ stick.matrix_world; stick.parent = arm; stick.matrix_world = mw
            objs.append(stick)
        if sx in OLD_KEYS:
            k = OLD_KEYS[sx]
            hand = target(sx, SHIFT, STATE["slide"])
            scale = k["lever"] / (hand - pivot).length
            act = bpy.data.actions.new(old.animation_data.action.name)
            fc = act.fcurves.new("rotation_euler", index=k["index"])
            for f, v in k["keys"]:
                kp = fc.keyframe_points.insert(f, v * scale); kp.interpolation = 'LINEAR'
            arm.animation_data_create().action = act
            report[f"{side.lower()}_loop_scale"] = round(scale, 3)
        bpy.data.objects.remove(old)
        arm.name = f"LWF_{ARM_NAME[MODE]}_{side}PlayingArm"
        report[f"{side.lower()}_pivot"] = [round(x, 4) for x in pivot]
        objs.append(arm)
    for o in list(bpy.data.objects):
        if o.name.startswith("LWF_Drummer_") and ("Shells" in o.name or "Cymbals" in o.name):
            o.location += SHIFT; o.name = "REVIEW_" + o.name
    bpy.data.objects.remove(body)
    sc = bpy.context.scene; sc.render.fps = 24; sc.frame_start = 1; sc.frame_end = 17
    name = f"lwf_{MODE}_{SEX}_kit_v2"
    # contact: instrument/hardware vs posed hand, and posed torso clearance to the instrument
    if MODE in INSTRUMENT:
        # hand contact: nearest distance from each playing arm to the moved instrument surface
        bpy.context.view_layer.update()
        for o in objs:
            if o.name.endswith("PlayingArm"):
                pts = [o.matrix_world @ v.co - SHIFT for v in o.data.vertices]
                gap = min(fixed_tree.find_nearest(p)[3] for p in pts)
                key = o.name.split("_")[2]
                report[key + "_hand_gap_mm"] = round(gap * 1000, 2)
                report[key + "_verts_inside_instrument"] = sum(inside(fixed_tree, p) for p in pts)
    report["shift_mm"] = [round(x * 1000, 1) for x in SHIFT]
    report["fret_slide_mm"] = round(STATE["slide"] * 1000, 1)
    report["fixed_clearance_mm"] = round(CLEARANCE * 1000, 2)
path = os.path.join(OUTDIR, name)
bpy.ops.wm.save_as_mainfile(filepath=path + ".blend")
export_objs = [o for o in objs if not o.name.startswith("REVIEW")]
report.update(file=name + ".glb", nodes=[o.name for o in export_objs], triangles=tris(export_objs),
              sha256=export(path + ".glb", export_objs, anim=MODE != "relaxed"))
json.dump(report, open(path + ".json", "w"), indent=1)
os.path.exists(os.path.join(OUTDIR, "_scratch.blend")) and os.remove(os.path.join(OUTDIR, "_scratch.blend"))
print("PERFORMER", json.dumps(report))
